name: ci-wf
on:
  push:
    branches:
      -develop
  pull_requests:
    branches:
      -develop
job:
 ci-job:
   runs-on: ubuntu-latest
   steps:
     -name: Welcome step
      run:  echo "welcome to github actions"
     -name: chechout/repository
      uses: actions/checkout@v4
     -name: Repository Information
      run:  |
        echo "Repository Name :${{github.repository}}"
        echo "Type of events :${{github.event_name}}"
        git -v
        git branch
        git log
        git config --local --list